import { Prop, Schema } from '@nestjs/mongoose';
import { Expose } from 'class-transformer';
import { SchemaTypes } from 'mongoose';

import { Relationship } from '../../core';

@Schema()
export class MongooseRelationship implements Relationship {
  @Expose()
  @Prop({
    type: SchemaTypes.String,
    required: true,
    index: true,
  })
  public readonly id1: string;

  @Expose()
  @Prop({
    type: SchemaTypes.String,
    required: true,
    index: true,
  })
  public readonly id2: string;

  @Expose()
  @Prop({ required: true })
  public readonly createdBy: string;

  // Generated by mongodb
  @Expose()
  public readonly createdAt: Date;

  @Expose()
  @Prop({ required: true })
  public readonly updatedBy: string;

  // Generated by mongodb
  @Expose()
  public readonly updatedAt: Date;
}
