import { Prop, Schema } from '@nestjs/mongoose';
import { SchemaTypes } from 'mongoose';

import { Relationship } from '../../core';

@Schema()
export class MongooseRelationship implements Relationship {
  @Prop({
    type: [{ type: SchemaTypes.String }],
    required: true,
    index: true,
  })
  public readonly id1: string;

  @Prop({
    type: [{ type: SchemaTypes.String }],
    required: true,
    index: true,
  })
  public readonly id2: string;

  @Prop({ required: true })
  public readonly createdBy: string;

  // Generated by mongodb
  public readonly createdAt: Date;

  @Prop({ required: true })
  public readonly updatedBy: string;

  // Generated by mongodb
  public readonly updatedAt: Date;
}
