import 'reflect-metadata';
import { Prop } from '@nestjs/mongoose';

import { NestApiIdProperty, NestApiMetaProperty } from '../../api';
import { Entity } from '../../core';

export class MongooseEntity implements Entity {
  // Generated by mongodb
  @NestApiIdProperty({ description: 'The UUID of the resource' })
  public readonly id: string;

  @NestApiMetaProperty({
    description: 'The UUID of the user who created the resource',
  })
  @Prop({ required: true })
  public readonly createdBy: string;

  // Generated by mongodb
  @NestApiMetaProperty({
    description: 'The time when the resource was created',
  })
  public readonly createdAt: Date;

  @NestApiMetaProperty({
    description: 'The UUID of the user who last updated the resource',
  })
  @Prop({ required: true })
  public readonly updatedBy: string;

  // Generated by mongodb
  @NestApiMetaProperty({
    description: 'The time when the resource was last updated',
  })
  public readonly updatedAt: Date;
}
