import { Observable } from 'rxjs';

import { Entity, Relationship, Timestamped } from '../core';

export type RelationshipAutoGeneratedColumns = keyof Timestamped;
export type RelationshipCreateDto = Omit<
  Relationship,
  RelationshipAutoGeneratedColumns
>;

export abstract class RelationshipRepository<TRelated extends Entity = Entity> {
  public abstract count(id1: string, id2set?: string[]): Observable<number>;

  public abstract find(
    id1: string,
    id2set?: string[],
  ): Observable<Relationship[]>;
  public abstract findRelated(
    id1: string,
    id2set?: string[],
  ): Observable<TRelated[]>;

  // TODO: maybe allow batch operations
  public abstract create(dto: RelationshipCreateDto): Observable<Relationship>;

  public abstract delete(id1: string, id2set?: string[]): Observable<void>;
}
