import { Observable } from 'rxjs';

import { Entity, Relationship, Timestamped } from '../core';

export type RelationshipAutoGeneratedColumns = keyof Timestamped;
export type RelationshipCreateDto = Omit<
  Relationship,
  RelationshipAutoGeneratedColumns
>;

export abstract class RelationshipRepository<TRelated extends Entity> {
  public abstract count(id1: string): Observable<number>;

  public abstract find(id1: string): Observable<Relationship[]>;
  public abstract findRelated(id1: string): Observable<TRelated[]>;

  public abstract create(dto: RelationshipCreateDto): Observable<Relationship>;

  public abstract read(id1: string, id2: string): Observable<Relationship>;
  public abstract readRelated(id1: string, id2: string): Observable<TRelated>;

  public abstract delete(id1: string, id2: string): Observable<void>;
}
