export const NEST_API_RESOURCE_METADATA_KEY: string =
  'NEST_API_RESOURCE_METADATA';

export const NEST_API_RESOURCE_FIELDS_METADATA_KEY: string =
  'NEST_API_RESOURCE_FIELDS_METADATA';

export const NEST_API_QUERY_METADATA_KEY: string = 'NEST_API_QUERY_METADATA';
