export const NEST_API_ENTITY_METADATA_KEY: string = 'NEST_API_ENTITY_METADATA';
export const NEST_API_ENTITY_FIELDS_METADATA_KEY: string =
  'NEST_API_ENTITY_FIELDS_METADATA';

export const NEST_API_QUERY_METADATA_KEY: string = 'NEST_API_QUERY_METADATA';
