export const NEST_API_ENTITY_METADATA_KEY: string = 'NEST_API_ENTITY_METADATA';
export const NEST_API_ENTITY_PROPERTIES_METADATA_KEY: string =
  'NEST_API_ENTITY_PROPERTIES_METADATA';

export const SWAGGER_API_PARAMETERS_METADATA_KEY = 'swagger/apiParameters';
